Task 1: 
Create a numpy array of int, characters, float and find their shapes

In [11]:
# integer array
import numpy as np 
array= np.random.randint(0,50,10) # array of size 10 range 0-50
print("Integer Array:\n", array)
print("Shape of Integer Array: ",np.shape(array))

# character array 
array = np.array(['a','b' ,'c', 'd'])
print("Character Array:\n", array)
print("Shape of Character Array : ",np.shape(array))

# float array 
array = np.random.rand(5, 2)
print("Float Array:\n", array)
print("Shape of Float Array : ",np.shape(array))




Integer Array:
 [ 6 45 12 35 27 14  8 14  9  0]
Shape of Integer Array:  (10,)
Character Array:
 ['a' 'b' 'c' 'd']
Shape of Character Array :  (4,)
Float Array:
 [[0.85419236 0.72271308]
 [0.54538045 0.74602798]
 [0.2364607  0.0080223 ]
 [0.66635628 0.3929054 ]
 [0.30854144 0.10142369]]
Shape of Float Array :  (5, 2)


Task 2:
Create a zeros, empty, identity , eye and a full array

In [15]:
arr = np.zeros((2,3), dtype=int)
print("Zero Array: \n", arr)

arr = np.empty((2,3), dtype = int)
print("Empty Array: \n", arr)

arr = np.identity(2, dtype = int)
print("Identity Array: \n", arr)

arr = np.eye(9,k = 3, dtype = int) #k is the diagnol
print("Eye Array: \n", arr)

arr = np.full([4, 2],11, dtype = int)
print("Full Array: \n", arr)

Zero Array: 
 [[0 0 0]
 [0 0 0]]
Empty Array: 
 [[0 0 0]
 [0 0 0]]
Identity Array: 
 [[1 0]
 [0 1]]
Eye Array: 
 [[0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
Full Array: 
 [[11 11]
 [11 11]
 [11 11]
 [11 11]]


Task 3:
Declare an array having the datatype of object, is it possible?


In [19]:
arr = np.empty((3,3), dtype = object) 
arr

array([[None, None, None],
       [None, None, None],
       [None, None, None]], dtype=object)

Task 4:
Create an array having 5 equally spaced numbers ranging from 5 to 15


In [20]:
arr = np.linspace(5, 15, num = 5, dtype = int)
arr

array([ 5,  7, 10, 12, 15])

Task 5:
Create a numpy array ranging from 1 to 100.

In [21]:
arr = np.arange(1,101, dtype= int)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

Task 6: 
Reshape the above array into (100,15). Is it possible?

In [24]:
#arr = arr.reshape(100, 15)

It is not possible

Task 7: 
Reshape the array into (100,10).

In [25]:
#arr = arr.reshape(100, 10)

It is not possible 

Task 8:
Flatten and ravel the reshaped array. What is the difference?

In [27]:
arr = np.reshape(arr, (50,-1))
print("Reshape Array: \n", arr)
arr = arr.flatten()
print("Flatten Array: \n", arr)
arr = np.ravel(arr) 
print("Ravel Array: \n", arr)

## order: C COLUMN WISE AND F ROW WISE

Reshape Array: 
 [[  1   2]
 [  3   4]
 [  5   6]
 [  7   8]
 [  9  10]
 [ 11  12]
 [ 13  14]
 [ 15  16]
 [ 17  18]
 [ 19  20]
 [ 21  22]
 [ 23  24]
 [ 25  26]
 [ 27  28]
 [ 29  30]
 [ 31  32]
 [ 33  34]
 [ 35  36]
 [ 37  38]
 [ 39  40]
 [ 41  42]
 [ 43  44]
 [ 45  46]
 [ 47  48]
 [ 49  50]
 [ 51  52]
 [ 53  54]
 [ 55  56]
 [ 57  58]
 [ 59  60]
 [ 61  62]
 [ 63  64]
 [ 65  66]
 [ 67  68]
 [ 69  70]
 [ 71  72]
 [ 73  74]
 [ 75  76]
 [ 77  78]
 [ 79  80]
 [ 81  82]
 [ 83  84]
 [ 85  86]
 [ 87  88]
 [ 89  90]
 [ 91  92]
 [ 93  94]
 [ 95  96]
 [ 97  98]
 [ 99 100]]
Flatten Array: 
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
Ravel Ar

Task 9: 
Take an array [[1 2 3] [4 5 6] [ 7 8 9]]. Sum it along 0 and 1 axis


In [28]:
arr = [[1,2,3],[4,5,6],[7,8,9]]
arr0 = np.sum(arr, axis = 0)
print("Along 0 Axis:\n", arr0)
arr1 = np.sum(arr, axis = 1)
print("Along 1 Axis: \n", arr1)

Along 0 Axis:
 [12 15 18]
Along 1 Axis: 
 [ 6 15 24]


Task 10: 
Find the number of bytes used by your array

In [29]:
arr = np.arange(1, 101)
print(arr.nbytes)

400


Task 11:
Find the maximum and minimum values in a 1D array.

In [30]:
maxA = arr.max()
print(maxA)
minA = arr.min()
print(minA)

100
1


Task 12:
Find the maximum and minimum values in 2D array

In [33]:
arr = np.array([[4,7,1],[2,13,9]])
maxA = arr.max()
minA = arr.min()
print(maxA)
print(minA)

13
1


Task 13:
Sort an array

In [34]:
arr = np.sort(arr)
print(arr)

[[ 1  4  7]
 [ 2  9 13]]


Task 14:
Is * and mul the same as dot product for numpy arrays and matrices? Check.

In [42]:
array1 = np.array([1,2,3,4,5,6])
array2 = np.array([1,2,3,4,5,6])
print(array1 * array2)
print(np.multiply(array1, array2).sum())
print(np.dot(array1, array2))

[ 1  4  9 16 25 36]
91
91


Task 15:
Take the square root and norm of an array.

In [36]:
array1 = np.matrix([[1,2,3],[4,5,6]])
array2 = np.matrix([[1,2,3],[4,5,6]])
print(np.multiply(array1, array2).sum())

91


Task 16:
Find the std, non-zero, zero values and mean of an array.

In [37]:
array1 = np.array([0,0,1,2,3,4,5,6,6])
arr1 = np.std(array1)
print(arr1)
arr2 = array1[np.nonzero(array1)]
print(arr2)
arr3 = array1[np.nonzero(array1 == 0)]
print(arr3)
arr4 = np.mean(array1)
print(arr4)

2.260776661041756
[1 2 3 4 5 6 6]
[0 0]
3.0


Task 17:
Convert some angles to radians and vice versa.

In [38]:
radian = np.radians(2.22)
print(radian)
degree = np.rad2deg(radian)
print(degree)
r2 = np.radians(degree)
print("back from degree to radian >> ", r2)

0.03874630939427412
2.22
back from degree to radian >>  0.03874630939427412


Task 18:
Save and load some of your arrays

In [39]:
array = np.array([1,0,1,0])
np.savetxt('file.txt', array)
loaded = np.loadtxt('file.txt')
print(array)
print(loaded)

[1 0 1 0]
[1. 0. 1. 0.]


Task 19:
Calculate the mean, std, var, max, min, of an array with shape (3,3,12,3) containing floats drawn from a normal distribution with mean 21 and sigma 4.5. see the np.random.normal.

In [40]:
a = np.random.normal(21, 4.5, (3,3,12,3))
print(np.mean(a))
print(np.std(a))
print(np.var(a))
print(np.max(a))
print(np.min(a))

21.141898497719673
4.6190197611526544
21.335343553918726
34.33874441120789
7.928832035230224
