## Task 1
## Implementing Gradient Descent From Scratch and Finding the Linear Relationship for the Given Dataset  

In [4]:
import pandas as pd
import numpy as np

In [5]:
def hypothesis(X1, thetas1):
    return np.dot(X1,thetas1)

In [6]:
def loss_fun(y_act, y_pred):
    return np.mean((y_act-y_pred)**2)

In [7]:
def gradient_descent(alpha, thetas2, g_thetas):
    return (thetas2-alpha*g_thetas)

In [8]:
def der_loss_fun(x,y,thetas3):
    hp=hypothesis(x,thetas3)
    diff = y-hp
    f1=np.dot(diff.T,X)
    f1=-2*f1/float(x.shape[0])
    return f1

In [9]:
df = pd.read_csv ("Advertising.csv")
df = df.iloc[: , 1:]
df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [10]:
one = np.ones(200)
X = df.iloc[: , :-1]
X['One'] = one
X = np.array(X)
Y = df.iloc[:,-1:]
Y = np.array(Y)
thetas = np.array([[100] , [50] , [75] , [1]])
print("X Shape: " , X.shape)
print("Y Shape: " , Y.shape)
print("Thetas Shape: " , thetas.shape)
alpha = 0.0001

X Shape:  (200, 4)
Y Shape:  (200, 1)
Thetas Shape:  (4, 1)


In [11]:
y_pred = hypothesis(X , thetas)
print(y_pred.shape)
MSE = loss_fun(Y , y_pred)
print("MSE",MSE)
g_thetas = der_loss_fun(X , Y , thetas)
g_thetas = g_thetas.T
print("g_thetas: ",g_thetas.shape)

(200, 1)

In [13]:
g_thetas = der_loss_fun(X , Y , thetas)
g_thetas = g_thetas.T
g_thetas.shape

(4, 1)

In [14]:
n_thetas = gradient_descent(alpha , thetas , g_thetas)
n_thetas

array([[-582.53413416],
       [ -39.71310866],
       [ -46.20737077],
       [  -2.6291955 ]])

In [15]:
# Finding gradient descent in a loop 
for i in range(100):
    y_pred = hypothesis(X , n_thetas)
    g_thetas = der_loss_fun(X , Y , n_thetas)
    g_thetas = g_thetas.T
    n_thetas = gradient_descent (alpha , n_thetas , g_thetas)
    print(loss_fun(Y , y_pred))

10245565150.439655
258935092657.69717
6545610952253.798
165467377974489.9
4182872848598500.5
1.0573942473738139e+17
2.6730016307310454e+18
6.757118015031627e+19
1.7081412650160984e+21
4.318034071271364e+22
1.0915618410801993e+24
2.7593743662878932e+25
6.975460855055013e+26
1.7633364553524422e+28
4.4575627609201046e+29
1.126833492679661e+31
2.8485380651433593e+32
7.200859010034225e+33
1.820315168573373e+35
4.6016000428851093e+36
1.163244877604102e+38
2.940582911729526e+39
7.433540458450766e+40
1.8791350356764578e+42
4.750291603367011e+43
1.2008328240708885e+45
3.035602004609516e+46
7.67374054545776e+47
1.939855549890413e+49
4.903787836126482e+50
1.2396353503280457e+52
3.1336914506415056e+53
7.921702220919224e+54
2.0025381268494114e+56
5.062243994599709e+57
1.279691703107727e+59
3.234950462185786e+60
8.177676285141211e+61
2.06724616671179e+63
5.225820348929106e+64
1.3210423973222382e+66
3.339481457452914e+67
8.441921642543259e+68
2.1340451182860062e+70
5.394682348068237e+71
1.36372925704

In [16]:
print(g_thetas)  # final thetas

[[9.41034181e+76]
 [1.16123904e+76]
 [1.53927734e+76]
 [4.83694180e+74]]


By looking at the inital thetas and final thetas we can see the linear relationship between features and outputs

## Task 2
## Write a code that finds out the relationship between two linear arrays

In [18]:
X = np.array([[1,2,3,4,5] , [1,1,1,1,1]]).T
Y = np.array([[3],[5],[7],[9],[11]])
n_thetas = np.array([[10] , [1]])
thetas = n_thetas
alpha = 0.08

In [22]:
for i in range(100):
    y_pred = hypothesis(X , n_thetas)
    g_thetas = der_loss_fun(X , Y , n_thetas)
    g_thetas = g_thetas.T
    n_thetas = gradient_descent (alpha , n_thetas , g_thetas)
    print(loss_fun(Y , y_pred))

0.0032012587154832276
0.0030304119632972816
0.002868685360626619
0.002715591590299211
0.002570669468149646
0.002433482522544196
0.002303617654959978
0.002180683876228796
0.002064311113557927
0.0019541490838762684
0.0018498662294253025
0.0017511487118442484
0.001657699461284009
0.0015692372773406
0.0014854959788240653
0.0014062235995834786
0.001331181627791238
0.0012601442862571028
0.0011928978514944956
0.0011292400094003463
0.0010689792455390271
0.0010119342681389407
0.0009579334620204285
0.000906814371775765
0.0008584232126182071
0.0008126144074046378
0.0007692501484214684
0.0007281999826004049
0.0006893404189045667
0.0006525545566950392
0.000617731733951751
0.0005847671942851643
0.0005535617717320773
0.0005240215923832013
0.0004960577919427018
0.00046958624836704115
0.00044452732877703273
0.00042080564988053866
0.00039834985118344777
0.0003770923803061784
0.0003569692897587051
0.0003379200445624973
0.00031988734013985284
0.00030281692992272744
0.00028665746216183214
0.000271360325445

In [23]:
n_thetas # Final

array([[2.00236705],
       [0.99145422]])

Q- Is linear regression good for classification? If yes, then why, and if no, then why?

A- Linear regression is not suitable because it only works for continuos values whereas classification problems mandate discrete values. 

Q- Why do we use mse (mean squared error) over squared error? What is the benefit of mse?

A- MSE calculates the average squared difference between the observed and predicted values, if we only took squared error it would increase w.r.t to the number of examples rather than telling us what the overall loss is. It's benefit is that its graph is a parabola so the minimum point has only one gradient. When a model has no error, the MSE equals zero. As model error increases, its value increases.

Q- Can you find a better estimator than mse?

A- MSE is a function of the parameter, there is not one "best" estimator, rather which estimator works best is situational.